version: "3"
services:
  bot:
    networks:
      - redis-net
    image: zx81/discord-bot
    depends_on:
      - "redis"
    environment:
      REDIS_HOST: "redis"
      FILE_STORE_PATH: "/server/volumes/bot"
    ports:
      - 9222:9222
    restart: always
    volumes:
      - ./volumes/bot:/server/volumes/bot

  redis:
    image: redislabs/redisearch:latest
    hostname: redis
    command:
      [
        "redis-server",
        "--loadmodule",
        "/usr/lib/redis/modules/redisearch.so",
        "--aof-use-rdb-preamble",
        "yes",
        "--appendonly",
        "yes",
      ]
    networks:
      - redis-net
    volumes:
      - ./volumes/redis:/data
    ports:
      - 6379
    restart: always

networks:
  ? redis-net
